<?php

namespace CodeChallenge\CodeChallengeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChallengesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChallengesRepository extends EntityRepository
{
}
