<?php

namespace CodeChallenge\CodeChallengeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProblemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProblemsRepository extends EntityRepository {
    
}
