<?php

namespace CodeChallenge\CodeChallengeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JoinchallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoinchallRepository extends EntityRepository
{
}
